language: rust
rust: nightly
env:
  - LLVM_CONFIG=$(which llvm-config-3.8) CXX=$(which g++-4.9)
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - llvm-3.8
      - llvm-3.8-dev
script:
  - cd $TRAVIS_BUILD_DIR/afl-plugin
  - cargo build --verbose
  - cd $TRAVIS_BUILD_DIR
  - cargo build --verbose
  - cargo build --example hello
  - cargo build --example deferred-init
  - cargo build --example integer-overflow
  - cargo build --example panic
