[package]
name = "afl-coverage"
version = "0.0.1"
readme = "README.md"
license = "Apache-2.0"
authors = ["Keegan McAllister <mcallister.keegan@gmail.com>"]
description = "Fuzzing Rust code with american-fuzzy-lop"
build = "build.rs"

[build-dependencies]
gcc = "0"

[dev-dependencies]
byteorder = "0"

[dev-dependencies.afl-coverage-plugin]
path = "plugin/"
