[package]
name = "afl"
version = "0.1.1"
readme = "README.md"
license = "Apache-2.0"
authors = ["Keegan McAllister <mcallister.keegan@gmail.com>",
           "Corey Farwell <coreyf@rwell.org>"]
description = "Fuzzing Rust code with american-fuzzy-lop"
build = "build.rs"
repository = "https://github.com/frewsxcv/afl.rs"
homepage = "https://github.com/frewsxcv/afl.rs"

[build-dependencies]
gcc = "0"

[dev-dependencies]
byteorder = "0.3"

[dev-dependencies.afl-plugin]
path = "plugin/"
version = "0.1.0"
